name: build-lint-test
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_PR_NUM: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [[ ! -z "${GH_PR_NUM}" ]]; then 
            echo "Checking out PR"
            git fetch origin pull/$GH_PR_NUM/head:tmp
            git checkout tmp
          fi
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: yarn-cache
        name: Cache npm deps
        with:
          path: |
           node_modules
           **/node_modules
          key: ${{ runner.os }}-yarn-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        id: dist
        name: Cache dist
        with:
          path: |
            packages/*/dist
          key: ${{ runner.os }}-dist-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock', 'package.json', 'packages/*/*', '!packages/*/dist', '!packages/*/node_modules') }}
      - name: Build dist
        run: yarn build:scss
        if: steps.dist.outputs.cache-hit != 'true'
  lint:
    runs-on: ubuntu-latest
    env:
      GH_PR_NUM: ${{ github.event.number }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [[ ! -z "${GH_PR_NUM}" ]]; then 
            echo "Checking out PR"
            git fetch origin pull/$GH_PR_NUM/head:tmp
            git checkout tmp
          fi
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: yarn-cache
        name: Cache npm deps
        with:
          path: |
           node_modules
           **/node_modules
          key: ${{ runner.os }}-yarn-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - uses: actions/cache@v2
        id: lint-cache
        name: Load lint cache
        with:
          path: '.eslintcache'
          key: ${{ runner.os }}-lint-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
      - name: MDLint
        run: yarn lint:md
